services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # 使用构建缓存加速重构建
      cache_from:
        - python:3.13-slim
    container_name: investnote-api
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      # 开发时代码同步（暂时注释以解决依赖覆盖问题）
      # 如需实时代码同步，请使用: docker-compose -f docker-compose.dev.yaml up
      # - .:/app
      # 专门的卷用于存储 Pyppeteer 下载的 Chromium
      - pyppeteer_data:/app/.pyppeteer
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - PYPPETEER_HOME=/app/.pyppeteer
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 添加额外的容器参数以支持 Chromium 无头浏览器
    cap_add:
      - SYS_ADMIN
    shm_size: 1gb
    networks:
      - investnote-net

volumes:
  pyppeteer_data:
    # 持久化存储 Pyppeteer 的数据

networks:
  investnote-net:
    driver: bridge