version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investnote-api
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - .:/app
      # 添加专门的卷用于存储 Pyppeteer 下载的 Chromium
      - pyppeteer_data:/app/.pyppeteer
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      # 设置 Pyppeteer 环境变量
      - PYPPETEER_HOME=/app/.pyppeteer
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # 添加额外的容器参数以支持 Chromium 无头浏览器
    cap_add:
      - SYS_ADMIN
    shm_size: 1gb
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - investnote-net

volumes:
  pyppeteer_data:
    # 持久化存储 Pyppeteer 的数据

networks:
  investnote-net:
    driver: bridge