# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0bshanmu.auth\"m\n\x0b\x41uthRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x13\n\x0bplatform_id\x18\x04 \x01(\t\x12\x13\n\x0bpermissions\x18\x05 \x03(\t\"\x8b\x01\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12(\n\tuser_info\x18\x03 \x01(\x0b\x32\x15.shanmu.auth.UserInfo\x12\x1b\n\x13granted_permissions\x18\x04 \x03(\t\x12\x12\n\nexpires_at\x18\x05 \x01(\x03\"\xc8\x01\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x13\n\x0bplatform_id\x18\x04 \x01(\t\x12\r\n\x05roles\x18\x05 \x03(\t\x12\x35\n\x08metadata\x18\x06 \x03(\x0b\x32#.shanmu.auth.UserInfo.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"=\n\x16TokenValidationRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\"w\n\x17TokenValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12(\n\tuser_info\x18\x03 \x01(\x0b\x32\x15.shanmu.auth.UserInfo\x12\x12\n\nexpires_at\x18\x04 \x01(\x03\"a\n\x16PermissionCheckRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08resource\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x14\n\x0cservice_name\x18\x04 \x01(\t\"O\n\x17PermissionCheckResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nconditions\x18\x03 \x03(\t2\x8c\x02\n\x0b\x41uthService\x12\x43\n\x0c\x41uthenticate\x12\x18.shanmu.auth.AuthRequest\x1a\x19.shanmu.auth.AuthResponse\x12Z\n\rValidateToken\x12#.shanmu.auth.TokenValidationRequest\x1a$.shanmu.auth.TokenValidationResponse\x12\\\n\x0f\x43heckPermission\x12#.shanmu.auth.PermissionCheckRequest\x1a$.shanmu.auth.PermissionCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINFO_METADATAENTRY']._loaded_options = None
  _globals['_USERINFO_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AUTHREQUEST']._serialized_start=27
  _globals['_AUTHREQUEST']._serialized_end=136
  _globals['_AUTHRESPONSE']._serialized_start=139
  _globals['_AUTHRESPONSE']._serialized_end=278
  _globals['_USERINFO']._serialized_start=281
  _globals['_USERINFO']._serialized_end=481
  _globals['_USERINFO_METADATAENTRY']._serialized_start=434
  _globals['_USERINFO_METADATAENTRY']._serialized_end=481
  _globals['_TOKENVALIDATIONREQUEST']._serialized_start=483
  _globals['_TOKENVALIDATIONREQUEST']._serialized_end=544
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_start=546
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_end=665
  _globals['_PERMISSIONCHECKREQUEST']._serialized_start=667
  _globals['_PERMISSIONCHECKREQUEST']._serialized_end=764
  _globals['_PERMISSIONCHECKRESPONSE']._serialized_start=766
  _globals['_PERMISSIONCHECKRESPONSE']._serialized_end=845
  _globals['_AUTHSERVICE']._serialized_start=848
  _globals['_AUTHSERVICE']._serialized_end=1116
# @@protoc_insertion_point(module_scope)
