# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.grpc.auth import CurrentUser_pb2 as auth_dot_CurrentUser__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth/CurrentUser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CurrentUserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.queryCurrentUser = channel.unary_unary(
                '/CurrentUserService/queryCurrentUser',
                request_serializer=auth_dot_CurrentUser__pb2.UserRequest.SerializeToString,
                response_deserializer=auth_dot_CurrentUser__pb2.CurrentUser.FromString,
                _registered_method=True)
        self.queryCurrentUserApp = channel.unary_unary(
                '/CurrentUserService/queryCurrentUserApp',
                request_serializer=auth_dot_CurrentUser__pb2.CurrentUserTypeRequest.SerializeToString,
                response_deserializer=auth_dot_CurrentUser__pb2.CurrentUserApps.FromString,
                _registered_method=True)
        self.updateCurrentUser = channel.unary_unary(
                '/CurrentUserService/updateCurrentUser',
                request_serializer=auth_dot_CurrentUser__pb2.CurrentUserUpdateRequest.SerializeToString,
                response_deserializer=auth_dot_CurrentUser__pb2.CurrentUser.FromString,
                _registered_method=True)


class CurrentUserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def queryCurrentUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryCurrentUserApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateCurrentUser(self, request, context):
        """*
        更新用户账户信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CurrentUserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'queryCurrentUser': grpc.unary_unary_rpc_method_handler(
                    servicer.queryCurrentUser,
                    request_deserializer=auth_dot_CurrentUser__pb2.UserRequest.FromString,
                    response_serializer=auth_dot_CurrentUser__pb2.CurrentUser.SerializeToString,
            ),
            'queryCurrentUserApp': grpc.unary_unary_rpc_method_handler(
                    servicer.queryCurrentUserApp,
                    request_deserializer=auth_dot_CurrentUser__pb2.CurrentUserTypeRequest.FromString,
                    response_serializer=auth_dot_CurrentUser__pb2.CurrentUserApps.SerializeToString,
            ),
            'updateCurrentUser': grpc.unary_unary_rpc_method_handler(
                    servicer.updateCurrentUser,
                    request_deserializer=auth_dot_CurrentUser__pb2.CurrentUserUpdateRequest.FromString,
                    response_serializer=auth_dot_CurrentUser__pb2.CurrentUser.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CurrentUserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CurrentUserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CurrentUserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def queryCurrentUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CurrentUserService/queryCurrentUser',
            auth_dot_CurrentUser__pb2.UserRequest.SerializeToString,
            auth_dot_CurrentUser__pb2.CurrentUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryCurrentUserApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CurrentUserService/queryCurrentUserApp',
            auth_dot_CurrentUser__pb2.CurrentUserTypeRequest.SerializeToString,
            auth_dot_CurrentUser__pb2.CurrentUserApps.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateCurrentUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CurrentUserService/updateCurrentUser',
            auth_dot_CurrentUser__pb2.CurrentUserUpdateRequest.SerializeToString,
            auth_dot_CurrentUser__pb2.CurrentUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
