# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/CurrentUser.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth/CurrentUser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61uth/CurrentUser.proto\"\x1c\n\x0bUserRequest\x12\r\n\x05token\x18\x01 \x01(\t\"5\n\x16\x43urrentUserTypeRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"\x7f\n\x16\x43urrentUserAppPlatform\x12\x35\n\x07\x63onfigs\x18\x01 \x03(\x0b\x32$.CurrentUserAppPlatform.ConfigsEntry\x1a.\n\x0c\x43onfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\x0f\x43urrentUserApps\x12\x0e\n\x06openId\x18\x01 \x01(\t\"M\n\x0b\x43urrentUser\x12\x17\n\x04user\x18\x01 \x01(\x0b\x32\t.UserInfo\x12\x10\n\x08\x63lientId\x18\x03 \x01(\t\x12\x13\n\x0b\x61uthorities\x18\x04 \x03(\t\"\x84\x02\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07unionId\x18\x02 \x01(\t\x12\x0e\n\x06userNo\x18\x03 \x01(\t\x12\x13\n\x0b\x63ountryCode\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\x12\x12\n\nplatformId\x18\x06 \x01(\x03\x12\x10\n\x08userName\x18\x07 \x01(\t\x12\x10\n\x08nickName\x18\x08 \x01(\t\x12\x13\n\x0b\x61\x63\x63ountType\x18\t \x01(\t\x12\x0e\n\x06\x61vatar\x18\n \x01(\t\x12\x12\n\nsuperAdmin\x18\x0b \x01(\x08\x12\x10\n\x08\x61uthUser\x18\x0c \x01(\x08\x12\x10\n\x08tenantId\x18\r \x01(\t\x12\x12\n\ncreateTime\x18\x0e \x01(\x03\"K\n\x18\x43urrentUserUpdateRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08nickName\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t2\xca\x01\n\x12\x43urrentUserService\x12\x30\n\x10queryCurrentUser\x12\x0c.UserRequest\x1a\x0c.CurrentUser\"\x00\x12\x42\n\x13queryCurrentUserApp\x12\x17.CurrentUserTypeRequest\x1a\x10.CurrentUserApps\"\x00\x12>\n\x11updateCurrentUser\x12\x19.CurrentUserUpdateRequest\x1a\x0c.CurrentUser\"\x00\x42\x18\n\x14ltd.shanmu.auth.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.CurrentUser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024ltd.shanmu.auth.grpcP\001'
  _globals['_CURRENTUSERAPPPLATFORM_CONFIGSENTRY']._loaded_options = None
  _globals['_CURRENTUSERAPPPLATFORM_CONFIGSENTRY']._serialized_options = b'8\001'
  _globals['_USERREQUEST']._serialized_start=26
  _globals['_USERREQUEST']._serialized_end=54
  _globals['_CURRENTUSERTYPEREQUEST']._serialized_start=56
  _globals['_CURRENTUSERTYPEREQUEST']._serialized_end=109
  _globals['_CURRENTUSERAPPPLATFORM']._serialized_start=111
  _globals['_CURRENTUSERAPPPLATFORM']._serialized_end=238
  _globals['_CURRENTUSERAPPPLATFORM_CONFIGSENTRY']._serialized_start=192
  _globals['_CURRENTUSERAPPPLATFORM_CONFIGSENTRY']._serialized_end=238
  _globals['_CURRENTUSERAPPS']._serialized_start=240
  _globals['_CURRENTUSERAPPS']._serialized_end=273
  _globals['_CURRENTUSER']._serialized_start=275
  _globals['_CURRENTUSER']._serialized_end=352
  _globals['_USERINFO']._serialized_start=355
  _globals['_USERINFO']._serialized_end=615
  _globals['_CURRENTUSERUPDATEREQUEST']._serialized_start=617
  _globals['_CURRENTUSERUPDATEREQUEST']._serialized_end=692
  _globals['_CURRENTUSERSERVICE']._serialized_start=695
  _globals['_CURRENTUSERSERVICE']._serialized_end=897
# @@protoc_insertion_point(module_scope)
