# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.grpc.auth import PlatformService_pb2 as auth_dot_PlatformService__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth/PlatformService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlatformInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getPlatformListByClientIds = channel.unary_unary(
                '/PlatformInfoService/getPlatformListByClientIds',
                request_serializer=auth_dot_PlatformService__pb2.PlatformQuery.SerializeToString,
                response_deserializer=auth_dot_PlatformService__pb2.PlatformQueryResp.FromString,
                _registered_method=True)
        self.getUserNumByClientId = channel.unary_unary(
                '/PlatformInfoService/getUserNumByClientId',
                request_serializer=auth_dot_PlatformService__pb2.CheckUserNumReq.SerializeToString,
                response_deserializer=auth_dot_PlatformService__pb2.CheckUserNumResp.FromString,
                _registered_method=True)
        self.getPlatformInfoByUserId = channel.unary_unary(
                '/PlatformInfoService/getPlatformInfoByUserId',
                request_serializer=auth_dot_PlatformService__pb2.PlatformInfoQuery.SerializeToString,
                response_deserializer=auth_dot_PlatformService__pb2.PlatformInfoQueryResp.FromString,
                _registered_method=True)


class PlatformInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getPlatformListByClientIds(self, request, context):
        """根据client_id列表查询对应的平台数组对象
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUserNumByClientId(self, request, context):
        """根据平台id获取平台普通用户数量作为统计数据返回
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPlatformInfoByUserId(self, request, context):
        """根据用户id获取平台clientId信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlatformInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getPlatformListByClientIds': grpc.unary_unary_rpc_method_handler(
                    servicer.getPlatformListByClientIds,
                    request_deserializer=auth_dot_PlatformService__pb2.PlatformQuery.FromString,
                    response_serializer=auth_dot_PlatformService__pb2.PlatformQueryResp.SerializeToString,
            ),
            'getUserNumByClientId': grpc.unary_unary_rpc_method_handler(
                    servicer.getUserNumByClientId,
                    request_deserializer=auth_dot_PlatformService__pb2.CheckUserNumReq.FromString,
                    response_serializer=auth_dot_PlatformService__pb2.CheckUserNumResp.SerializeToString,
            ),
            'getPlatformInfoByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.getPlatformInfoByUserId,
                    request_deserializer=auth_dot_PlatformService__pb2.PlatformInfoQuery.FromString,
                    response_serializer=auth_dot_PlatformService__pb2.PlatformInfoQueryResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PlatformInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PlatformInfoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlatformInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getPlatformListByClientIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PlatformInfoService/getPlatformListByClientIds',
            auth_dot_PlatformService__pb2.PlatformQuery.SerializeToString,
            auth_dot_PlatformService__pb2.PlatformQueryResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getUserNumByClientId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PlatformInfoService/getUserNumByClientId',
            auth_dot_PlatformService__pb2.CheckUserNumReq.SerializeToString,
            auth_dot_PlatformService__pb2.CheckUserNumResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getPlatformInfoByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PlatformInfoService/getPlatformInfoByUserId',
            auth_dot_PlatformService__pb2.PlatformInfoQuery.SerializeToString,
            auth_dot_PlatformService__pb2.PlatformInfoQueryResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
