# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/PlatformService.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'auth/PlatformService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61uth/PlatformService.proto\".\n\rPlatformQuery\x12\x1d\n\tclientIds\x18\x01 \x03(\x0b\x32\n.ClientIds\"\x1d\n\tClientIds\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"W\n\x11PlatformQueryResp\x12#\n\x0cplatformInfo\x18\x01 \x03(\x0b\x32\r.PlatformInfo\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\".\n\x0cPlatformInfo\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"2\n\x0f\x43heckUserNumReq\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"B\n\x10\x43heckUserNumResp\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07userNum\x18\x03 \x01(\x03\"2\n\x11PlatformInfoQuery\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\r\n\x05token\x18\x02 \x01(\t\")\n\x15PlatformInfoQueryResp\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t2\xe1\x01\n\x13PlatformInfoService\x12\x42\n\x1agetPlatformListByClientIds\x12\x0e.PlatformQuery\x1a\x12.PlatformQueryResp\"\x00\x12=\n\x14getUserNumByClientId\x12\x10.CheckUserNumReq\x1a\x11.CheckUserNumResp\"\x00\x12G\n\x17getPlatformInfoByUserId\x12\x12.PlatformInfoQuery\x1a\x16.PlatformInfoQueryResp\"\x00\x42\x18\n\x14ltd.shanmu.auth.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.PlatformService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024ltd.shanmu.auth.grpcP\001'
  _globals['_PLATFORMQUERY']._serialized_start=30
  _globals['_PLATFORMQUERY']._serialized_end=76
  _globals['_CLIENTIDS']._serialized_start=78
  _globals['_CLIENTIDS']._serialized_end=107
  _globals['_PLATFORMQUERYRESP']._serialized_start=109
  _globals['_PLATFORMQUERYRESP']._serialized_end=196
  _globals['_PLATFORMINFO']._serialized_start=198
  _globals['_PLATFORMINFO']._serialized_end=244
  _globals['_CHECKUSERNUMREQ']._serialized_start=246
  _globals['_CHECKUSERNUMREQ']._serialized_end=296
  _globals['_CHECKUSERNUMRESP']._serialized_start=298
  _globals['_CHECKUSERNUMRESP']._serialized_end=364
  _globals['_PLATFORMINFOQUERY']._serialized_start=366
  _globals['_PLATFORMINFOQUERY']._serialized_end=416
  _globals['_PLATFORMINFOQUERYRESP']._serialized_start=418
  _globals['_PLATFORMINFOQUERYRESP']._serialized_end=459
  _globals['_PLATFORMINFOSERVICE']._serialized_start=462
  _globals['_PLATFORMINFOSERVICE']._serialized_end=687
# @@protoc_insertion_point(module_scope)
