# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/UserAccount.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'auth/UserAccount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61uth/UserAccount.proto\"]\n\x17UserAccountValidRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x13\n\x0b\x63ountryCode\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0f\n\x07smsCode\x18\x04 \x01(\t\"I\n\x14UserAccountIdRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\x03\x12\x12\n\nplatformId\x18\x03 \x01(\t\"K\n\x15UserAccountIdsRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07userIds\x18\x02 \x03(\x03\x12\x12\n\nplatformId\x18\x03 \x01(\t\"1\n\x13UserAccountResponse\x12\x1a\n\x04user\x18\x01 \x01(\x0b\x32\x0c.UserAccount\"3\n\x14UserAccountsResponse\x12\x1b\n\x05users\x18\x01 \x03(\x0b\x32\x0c.UserAccount\"\xaa\x01\n\x0bUserAccount\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\x0f\n\x07unionId\x18\x02 \x01(\t\x12\x0e\n\x06userNo\x18\x03 \x01(\t\x12\x13\n\x0b\x63ountryCode\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\x12\x10\n\x08userName\x18\x06 \x01(\t\x12\x10\n\x08nickName\x18\x07 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x08 \x01(\t\x12\x12\n\ncreateTime\x18\t \x01(\x03\")\n\x18UserAccountLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\":\n\x19UserAccountLogoutResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc0\x02\n\x12UserAccountService\x12\x45\n\x14queryUserAccountById\x12\x15.UserAccountIdRequest\x1a\x14.UserAccountResponse\"\x00\x12H\n\x15queryUserAccountByIds\x12\x16.UserAccountIdsRequest\x1a\x15.UserAccountsResponse\"\x00\x12N\n\x1avalidOrregisterUserAccount\x12\x18.UserAccountValidRequest\x1a\x14.UserAccountResponse\"\x00\x12I\n\x0elogoutUserInfo\x12\x19.UserAccountLogoutRequest\x1a\x1a.UserAccountLogoutResponse\"\x00\x42\x18\n\x14ltd.shanmu.auth.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.UserAccount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024ltd.shanmu.auth.grpcP\001'
  _globals['_USERACCOUNTVALIDREQUEST']._serialized_start=26
  _globals['_USERACCOUNTVALIDREQUEST']._serialized_end=119
  _globals['_USERACCOUNTIDREQUEST']._serialized_start=121
  _globals['_USERACCOUNTIDREQUEST']._serialized_end=194
  _globals['_USERACCOUNTIDSREQUEST']._serialized_start=196
  _globals['_USERACCOUNTIDSREQUEST']._serialized_end=271
  _globals['_USERACCOUNTRESPONSE']._serialized_start=273
  _globals['_USERACCOUNTRESPONSE']._serialized_end=322
  _globals['_USERACCOUNTSRESPONSE']._serialized_start=324
  _globals['_USERACCOUNTSRESPONSE']._serialized_end=375
  _globals['_USERACCOUNT']._serialized_start=378
  _globals['_USERACCOUNT']._serialized_end=548
  _globals['_USERACCOUNTLOGOUTREQUEST']._serialized_start=550
  _globals['_USERACCOUNTLOGOUTREQUEST']._serialized_end=591
  _globals['_USERACCOUNTLOGOUTRESPONSE']._serialized_start=593
  _globals['_USERACCOUNTLOGOUTRESPONSE']._serialized_end=651
  _globals['_USERACCOUNTSERVICE']._serialized_start=654
  _globals['_USERACCOUNTSERVICE']._serialized_end=974
# @@protoc_insertion_point(module_scope)
